// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnGqnZywRhtzupawKRscGgxy8fNNBW1SQ',
    appId: '1:675219167797:web:95398a6b0dcf45c864ef7c',
    messagingSenderId: '675219167797',
    projectId: 'sanrakshaan25',
    authDomain: 'sanrakshaan25.firebaseapp.com',
    storageBucket: 'sanrakshaan25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaTgA7LkQehVe7jy3z1opRXrB4r-qGqOU',
    appId: '1:675219167797:android:8570daa5854c405164ef7c',
    messagingSenderId: '675219167797',
    projectId: 'sanrakshaan25',
    storageBucket: 'sanrakshaan25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBz_DejSNfsHJ7T_SeqoKpDTQUfonWVyY',
    appId: '1:675219167797:ios:805e0736632419c164ef7c',
    messagingSenderId: '675219167797',
    projectId: 'sanrakshaan25',
    storageBucket: 'sanrakshaan25.firebasestorage.app',
    iosBundleId: 'com.example.sanrakshan25',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBz_DejSNfsHJ7T_SeqoKpDTQUfonWVyY',
    appId: '1:675219167797:ios:805e0736632419c164ef7c',
    messagingSenderId: '675219167797',
    projectId: 'sanrakshaan25',
    storageBucket: 'sanrakshaan25.firebasestorage.app',
    iosBundleId: 'com.example.sanrakshan25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnGqnZywRhtzupawKRscGgxy8fNNBW1SQ',
    appId: '1:675219167797:web:b14c7ccc65bb529864ef7c',
    messagingSenderId: '675219167797',
    projectId: 'sanrakshaan25',
    authDomain: 'sanrakshaan25.firebaseapp.com',
    storageBucket: 'sanrakshaan25.firebasestorage.app',
  );
}
